services:
  - type: web
    name: bragfy
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run setup && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: OPENROUTER_API_KEY
        sync: false
