services:
  - type: web
    name: bragfy-agent
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start:prod
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: RENDER
        value: true
